image: node:12

stages:
  - staging

staging:
  stage: staging
  before_script:
    - export REACT_APP_BASE_URL=$REACT_APP_BASE_URL
    - export REACT_APP_PUBLIC_KEY=$REACT_APP_PUBLIC_KEY
    - export REACT_APP_ENVIRONMENT=$REACT_APP_ENVIRONMENT
    - export REACT_APP_WEBAPP_NAME=$REACT_APP_WEBAPP_NAME
    - export REACT_APP_PAYMENT_GATEWAY=$REACT_APP_PAYMENT_GATEWAY
    - npm install
    - CI=false npm run build
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y  )'
    - 'which rsync || ( apt-get update -y && apt-get install rsync -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $SERVER_HOST >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - ssh -p22 $SERVER_USER@$SERVER_HOST "rm -rf /var/www/_tmp"
    - ssh -p22 $SERVER_USER@$SERVER_HOST "mkdir /var/www/_tmp"
    - rsync -avuz --exclude=".*" --exclude="node_modules" build/* $SERVER_USER@$SERVER_HOST:/var/www/_tmp
    - ssh -p22 $SERVER_USER@$SERVER_HOST "mv /var/www/html /var/www/_old && mv /var/www/_tmp /var/www/html"
    - ssh -p22 $SERVER_USER@$SERVER_HOST "rm -rf /var/www/_old"
  artifacts:
    paths:
    - build/
  only:
    - snapshot
